### PR TITLE
Update README to include instructions on how to get started

### LINKED ISSUE #10: Add How To Get Started Guide

### PR DESCRIPTION
**Pull request by skoehnen**
Closes #10

### CODE REVIEW

**Review by lzehl — APPROVED** [review]
I would integrate this as is and make some changes afterwards. Thanks a lot for adding this part.
@olinux your feedback would be great here as well.

**Comment by skoehnen** [comment]
@lzehl what changes are required?

**Comment by lzehl** [comment]
> @lzehl what changes are required?

I need to make some extensions. I did not yet have the chance to update the READMEs

**Comment by skoehnen** [comment]
> > @lzehl what changes are required?
> 
> I need to make some extensions. I did not yet have the chance to update the READMEs

Ah, I thought you meant changes to the Getting Started part, then I would have done that now.

**Pull request merged**
